[tool.poetry]
name = "isolate"
version = "0.1.0"
description = "Managed isolated environments for Python"
authors = ["Features & Labels <hello@fal.ai>"]

[tool.poetry.dependencies]
python = ">=3.7"
virtualenv = "^20"
cloudpickle = "^2.2.0"
importlib-metadata = "^5.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic=true
force_grid_wrap=0
include_trailing_comma=true
multi_line_output=3
use_parentheses=true

[tool.poetry.plugins."isolate.backends"]
"virtualenv" = "isolate.backends.virtual_env:VirtualPythonEnvironment"
"conda" = "isolate.backends.conda:CondaEnvironment"
