[tool.poetry]
name = "insulate"
version = "0.1.1"
readme = "README.md"
description = "Managed isolated environments for Python"
authors = ["Features & Labels <hello@fal.ai>"]

[tool.poetry.dependencies]
python = ">=3.7"
virtualenv = ">=20.4"
importlib-metadata = ">=4.4"
flask = { version = "*", optional = true }
marshmallow = { version = "*", optional = true }

[tool.poetry.extras]
server = ["flask", "marshmallow"]

[tool.poetry.plugins."insulate.backends"]
"virtualenv" = "insulate.backends.virtual_env:VirtualPythonEnvironment"
"conda" = "insulate.backends.conda:CondaEnvironment"
"local" = "insulate.backends.local:LocalPythonEnvironment"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
atomic=true
force_grid_wrap=0
include_trailing_comma=true
multi_line_output=3
use_parentheses=true
