name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Install conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        python-version: ${{ matrix.python }}
        # PyJokes is available on conda-forge
        conda-channels: anaconda, conda-forge

    - name: Install dependencies
      run: |
        python -m pip install pytest
        python -m pip install -e .

    - name: Test
      run: python -m pytest
